
services:

  webapi:
    image: vnalivaika/img-erp-webapi
    hostname: webapi
    container_name: ctn-erp-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
    networks:
      - default
    volumes:
    ports:
      - 8080:80
  