

services:
  postgresql:
    extends:
      file: ./01-docker-compose.psql.yml
      service: postgresql

  pgadmin:
    extends:
      file: ./02-docker-compose.pgadm.yml
      service: pgadmin

networks:
  default:
    driver: bridge

volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local        