
services:

  webapi:
    build: ../app/App.WebApi/.
    image: erpcontainerregistry.azurecr.io/img-erp-webapi
    hostname: webapi
    container_name: ctn-erp-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=PROD 
    networks:
      - default
    volumes:
    ports:
      - 8080:80
      - 443:443
  