
version: "3"

services:
  postgresql:
    image: postgres:14
    hostname: postgres
    container_name: ctn-postgres
    environment:
      - POSTGRES_USER=TLM
      - POSTGRES_PASSWORD=TLM
      - POSTGRES_DB=erpx  # if not provided, then the db with the name $POSTGRES_USER will be created
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.20
    hostname: pgadmin
    container_name: ctn-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: TLM@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: TLM
    networks:
      - backend
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80

networks:
  backend:

volumes:
  db-data:
  pgadmin-data:     
