
services:

  pgadmin:
    image: dpage/pgadmin4:6.20
    hostname: pgadmin
    container_name: ctn-pgadmin$BLA
    environment:
      PGADMIN_DEFAULT_EMAIL: TLM@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: TLM
    networks:
      - default
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    mem_limit: 256m
    mem_reservation: 128m
